### PR TITLE
feat: Blur Window

### PR DESCRIPTION
**Pull request by not-nef**
Im Back.
Screenshot 2022-01-12 162843

### CODE REVIEW

**Comment by im-coder-lg** [comment]
Any toggle for that though?

**Comment by im-coder-lg** [comment]
Wait I'll try activating checks for macOS and Linux.

**Comment by im-coder-lg** [comment]
Can you try opening a Gitpod env and test it? Also try testing the same on your Mac Mini. But don't use your dad's Mac Mini.
I expect you have Git and Python 3.8+ on your Mac mini, so try these steps:
```shell
git clone https://github.com/sumeshir26/TimerX.git
cd TimerX
git checkout Blur
git fetch && git pull
pip install -r requirements.txt
python main.py
```
Check the TimerX console on Gitpod for the error. I will test on my RasPi soon, kinda busy.

**Comment by sumeshir26** [comment]
@not-nef This is definitely not intended:-
image
FYI, OS in Dark Mode, TimerX in Light

**Comment by im-coder-lg** [comment]
lol that's abnormal

**Comment by not-nef** [comment]
> @not-nef This is definitely not intended LOL 😂:-
> 
> image
> 
> FYI, OS in Dark Mode, TimerX in Light

Well no it isnt lmao

**Comment by not-nef** [comment]
> Wait I'll try activating checks for macOS and Linux.

It literally did checks for macos image

**Comment by not-nef** [comment]
> Can you try opening a Gitpod env and test it? Also try testing the same on your Mac Mini. But don't use your dad's Mac Mini.
> I expect you have Git and Python 3.8+ on your Mac mini, so try these steps:
> ```shell
> git clone https://github.com/sumeshir26/TimerX.git
> cd TimerX
> git checkout Blur
> git fetch && git pull
> pip install -r requirements.txt
> python main.py
> ```
> Check the TimerX console on Gitpod for the error. I will test on my RasPi soon, kinda busy.

Uhm, why?

**Comment by sumeshir26** [comment]
> Uhm, why?

To make sure that blur isnt broken on Mac

**Comment by not-nef** [comment]
I was planning to disable it for mac, but ok

**Comment by not-nef** [comment]
And the dmg still doesn't work i thought you guys dropped macos support

**Comment by im-coder-lg** [comment]
> It literally did checks for macos

That was just the DMG build. The real test has to be done on a real/imaginary(VM) computer.

**Comment by not-nef** [comment]
But it doesn't run the dmg so i thought you dropped macos support @im-coder-lg

**Comment by sumeshir26** [comment]
@not-nef First, I'll create a PR in the Sun Valley TTk Theme Repo to make the Button and AccentButton background transparent. 
Meanwhile, you can figure out how to make acrylic work properly on both light and dark theme.

**Comment by not-nef** [comment]
Ill fix macos tomorrow

**Comment by not-nef** [comment]
img

@sumeshir26 Is there a way to make the corners of the buttons transparent? I think it has to do something with the custom theme because the ttk.Button has no `bg` parameter

**Comment by not-nef** [comment]
And btw the labels are fixed i just took the old screenshot

**Comment by not-nef** [comment]
@im-coder-lg Can you manually run the checks on this one pls? It still annoys me

**Comment by im-coder-lg** [comment]
Just update your branch and make another change, the checks autoupdate.

**Comment by not-nef** [comment]
@sumeshir26 im gonna make the bg of the button transparent like rdbende told us sometime next week. And @im-coder-lg can you pls disable the comments of that netlify bot? (What even is netlify?)

**Comment by im-coder-lg** [comment]
Netlify is just our website deployer, it makes a comment on all PRs and it will safely ignore if you don't even touch the docs, so don't worry, it will just keep cancelling.

**Comment by im-coder-lg** [comment]
Also, it's not `acrillic`, it's `acrylic`.

**Comment by sumeshir26** [comment]
Sorry, no spellcheck in VSCode! And does the acrilic work for you?

**Comment by im-coder-lg** [comment]
Is this intended?
image
I've never seen TimerX like that.

**Comment by sumeshir26** [comment]
Wow, the theme did not load at all! And it seems that yoir entire background became transperent. Try rerunning the program

**Comment by sumeshir26** [comment]
Windows 7 is wierd.. You should reallay upgrade to Zorin/Manjaro/Mint soon...

**Comment by im-coder-lg** [comment]
The laptop doesn't support the latest LTS in terms of Ubuntu or Arch. And most laptops are costly, especially Linux laptops since they are made to be customisable before purchase. Having a hard time to select the computer. Maybe I will try finding a cheap but nice computer for my work.

**Comment by not-nef** [comment]
Is there some way to detect windows 7? I will exclude the blur for it.

**Comment by im-coder-lg** [comment]
I think it's `win32` but Windows 10 could well enough be using that.

**Comment by im-coder-lg** [comment]
Don't do anything though for now, I'll find a solution tomorrow.

**Comment by not-nef** [comment]
Finally understood how to fix merge conflicts!!

**Comment by not-nef** [comment]
@sumeshir26 Did you even test your changes on windows 11?

**Comment by not-nef** [comment]
Fixed green lines, and everything is transparent!!

Screenshot 2022-01-18 195100

**Comment by not-nef** [comment]
It should also work with windows 7 now! @im-coder-lg

**Comment by not-nef** [comment]
@sumeshir26 if you change something in someone else‘s pr, please test it next time

**Comment by not-nef** [comment]
@sumeshir26 merge?

**Review by sumeshir26 — APPROVED** [review]
LGTM🎉

**Comment by im-coder-lg** [comment]
Wait it fails for Windows 7! Add a toggle!

**Comment by sumeshir26** [comment]
@im-coder-lg Just waiting on your review/conformation that it works on Win 7

**Review by im-coder-lg — COMMENTED** [review]
It fails for Windows 7, care to add a blur toggle?

**Comment by im-coder-lg** [comment]
Also, before merging, @not-nef can you get isort and black formatters? Just do this:
```shell
# I know you got isort, you need black now.
pip install black
isort *.py
black *.py
```
That'd format the code.

**Comment by sumeshir26** [comment]
@not-nef When OS _and_ TImerX in light, this happens:

**Comment by sumeshir26** [comment]
image

**Comment by im-coder-lg** [comment]
Almost the same for me lol.

**Comment by sumeshir26** [comment]
I guess this is because Windows 7 is Light Mode

**Comment by sumeshir26** [comment]
@not-nef Maby we can totally disable it on light mode

**Comment by not-nef** [comment]
Why?

**Comment by sumeshir26** [comment]
Look at my screenshot

**Comment by not-nef** [comment]
Hmmmm, okay

**Comment by not-nef** [comment]
Will look into it after school

**Comment by im-coder-lg** [comment]
> I guess this is because Windows 7 is Light Mode

Actually, Windows 7 has two themings only - Aero, which makes everything transparent and animated and Classic, which is just plain white. There is also the Windows 95-ish theme that makes the system go retro. However, there's nothing with the theming on Windows 7. It's just normal, I hope to switch to something like Zorin but this computer is unsupported. A lot of things in my mind is similar to this(reverse the sentence to fully understand it though).

**Comment by not-nef** [comment]
@im-coder-lg try it now

**Comment by not-nef** [comment]
@sumeshir26 Merge?

**Comment by im-coder-lg** [comment]
Umm... Nothing changed really. I don't understand what is happening.

**Comment by not-nef** [comment]
Send a screenshot pls

**Comment by not-nef** [comment]
Are you sure you are on the latest commit?

**Comment by im-coder-lg** [comment]
I `git pull`ed and then executed the file. I will try again tomorrow.

**Comment by not-nef** [comment]
Can you check if the file has exactly 702 lines?

**Comment by not-nef** [comment]
Atleast its fixed for window 11

**Comment by not-nef** [comment]
Why dont you just use windows 11 and well make this app windows only?

**Comment by not-nef** [comment]
Its easy to bypass the windows 11 requirements

**Comment by not-nef** [comment]
I have done that for my laptop too

**Comment by not-nef** [comment]
> Almost the same for me lol.

Did the theme atleast load?

**Comment by im-coder-lg** [comment]
> Did the theme atleast load?

Nope.

**Comment by im-coder-lg** [comment]
> Can you check if the file has exactly 702 lines?

Yeah it does.

**Comment by sumeshir26** [comment]
@im-coder-lg Run `gh pr checkout 46`

**Comment by im-coder-lg** [comment]
That is what I ran, `git pull`ed with `--force` and ran the main python file. Wait, it could be missing modules, right?

**Comment by sumeshir26** [comment]
No, run it again. GH CLI creates a local branch if the PR is from another fork, so `git pull` wont do anything. Also, try to install the requirements again.

**Comment by im-coder-lg** [comment]
Nothing changed. Is there a module error?

**Comment by im-coder-lg** [comment]
Before you ask, the branch is fully updated and I haven't added any new changes.

**Comment by im-coder-lg** [comment]
It's all with the theming! I changed the theme and the old UI is back! So, you might've done something(accidentally) to theming!

**Comment by sumeshir26** [comment]
For me, it works absolutely beautifully. It is nice and acrilic. can you try to replace all instances of `GlobalBlur` with `Win7Blur`?

**Comment by im-coder-lg** [comment]
Also, look here:
https://github.com/TimerX-App/TimerX/blob/6fb4d1dfb613cc3990e65882de4abf15c908d01e/main.py#L133-L144
The title's being used twice, so it's failing. Can we fix this in this PR?

**Comment by im-coder-lg** [comment]
Also, look here:
https://github.com/TimerX-App/TimerX/blob/6fb4d1dfb613cc3990e65882de4abf15c908d01e/main.py#L133-L144
The title's being used twice, so it's failing. Can we fix this in this PR?

**Comment by sumeshir26** [comment]
Ok

**Comment by sumeshir26** [comment]
Fixed

**Comment by im-coder-lg** [comment]
image
Umm... Is that normal?

**Comment by im-coder-lg** [comment]
image
Umm... Is that normal?

**Comment by im-coder-lg** [comment]
`GlobalBlur` seems to work. However, `Win7Blur` seems a bad way(check the error above). The Toast Notifier was causing the error, the theming works now. But the toast fails.

**Comment by im-coder-lg** [comment]
Or it was just CMD.

**Comment by im-coder-lg** [comment]
Nothing seems to work yet again.

**Comment by im-coder-lg** [comment]
It seems to have fixed itself. It's puzzling to myself.

**Comment by sumeshir26** [comment]
Ok, So approve this PR

**Comment by im-coder-lg** [comment]
One minute, apologies. I want to test this again, final test run.

**Review by im-coder-lg — APPROVED** [review]
Yup, everything's good. The toast notif fails but we'll fix that later.

**Comment by not-nef** [comment]
Lets go

**Comment by im-coder-lg** [comment]
@not-nef can you restore this branch?

**Comment by im-coder-lg** [comment]
I'm thinking of reverting this merge, making another PR from this branch and fixing this,

**Comment by not-nef** [comment]
No, he fixed it in #65

**Pull request merged**
