### PR TITLE
feat: Re-add System Theme

### PR DESCRIPTION
**Pull request by sumeshir26**

### CODE REVIEW

**Comment by im-coder-lg** [comment]
This seems to work. System theming is back. But GitHub's Dark mode is screwed up, it will never be back for me lol. Just a joke. Anything else to add?

**Comment by sumeshir26** [comment]
@im-coder-lg Now its ready. Test it after pulling

**Comment by not-nef** [comment]
Did you compile and test it @sumeshir26 ? I cant get to my pc atm.

**Comment by sumeshir26** [comment]
Yes, if darkdetect fails to work, it will automaticallay fallback to light

**Comment by not-nef** [comment]
Whats with the blur? Does it work?

**Comment by sumeshir26** [comment]
Well, darkdetect does not work after compile at all. It just falls back to Light

**Comment by sumeshir26** [comment]
Blur works 100%!

**Comment by not-nef** [comment]
Thats because the BlurWindow module blurs the window with the corresponding hwnd and the command prompt has the same hwnd as the tkinter window that you launch with it.

**Review by not-nef — APPROVED** [review]

**Pull request merged**
