### PR TITLE
style(docs): Prettier formatting

### PR DESCRIPTION
**Pull request by im-coder-lg**
The same thing happened again. Hopefully the same doesn't happen locally.

### CODE REVIEW

**Comment by im-coder-lg** [comment]
From now, no one uses Gitpod except for tests. It's too hard to push. Github's APIs need to fix themselves.

**Comment by not-nef** [comment]
Why does ubuntu build fail? (i have art class rn so i cant talk)

**Comment by not-nef** [comment]
and why is the windows build not starting? Nothing works!

**Comment by im-coder-lg** [comment]
I think it's due to the new tests. Fixing,

**Comment by im-coder-lg** [comment]
@TimerX-App/reviewers time for review

**Comment by sumeshir26** [comment]
I think the readme should be kept in the root dir

**Comment by sumeshir26** [comment]
@im-coder-lg 28K Addittions??!!

**Comment by im-coder-lg** [comment]
Prettier. I just did `npx prettier --write .` from the docs root, never expected that lol.

**Comment by im-coder-lg** [comment]
Why did you delete the README from the docs? GitHub accepted it!

**Comment by sumeshir26** [comment]
I reallay think we should keep it in root

**Comment by im-coder-lg** [comment]
> I reallay think we should keep it in root

Okay, what about contributing.md and code of conduct?

**Comment by sumeshir26** [comment]
FYI 
image

**Comment by im-coder-lg** [comment]
I hate the package lockfile.

**Comment by sumeshir26** [comment]
> Okay, what about contributing.md and code of conduct?

Those can be kept in the docs folder

**Comment by im-coder-lg** [comment]
Okay, but we can't remove the lockfile, `npm` recommends we commit it.

**Comment by im-coder-lg** [comment]
Maybe that's why I hesitated in choosing Prettier. Should have just done `npx prettier --write docs/` and the same to `src` if you consider the root of documentation `docs` as root.

**Comment by not-nef** [comment]
> I reallay think we should keep it in root

Why?

**Comment by im-coder-lg** [comment]
IDK, maybe it's easy to edit?

**Comment by sumeshir26** [comment]
@im-coder-lg Removing the Lockfile and Merging since the lockfile is not really necessary...

**Comment by im-coder-lg** [comment]
Alright, fixed merge conflicts. Ready to merge.

**Pull request merged**
