### PR TITLE
release: v1.0

### PR DESCRIPTION
**Pull request by sumeshir26**

### CODE REVIEW

**Comment by im-coder-lg** [comment]
Wait, I'll update anything in the docs that say v0.9, including the announcement bar.

**Comment by im-coder-lg** [comment]
Alright, I think it's ready now.

**Comment by im-coder-lg** [comment]
Let's merge #65 then tis.

**Review by im-coder-lg — APPROVED** [review]

**Comment by sumeshir26** [comment]
Can you also update the banner in the README?

**Comment by im-coder-lg** [comment]
Can you please elaborate?

**Comment by sumeshir26** [comment]
It currentley says Verswion 0.9 is out! But that needs to be changed to 1.0

**Comment by im-coder-lg** [comment]
Where?

**Comment by im-coder-lg** [comment]
Share line permalink here(just post the link, no markdown).

**Comment by im-coder-lg** [comment]
Firstly, when Inchecked on my phone as well as my PC, I noticed that it wasn't there. Are you talking about the badge? That would be updated automatically.

**Pull request merged**
