### PR TITLE
fix: Fix App after Compile

### PR DESCRIPTION
**Pull request by sumeshir26**
Issue fixed! Caused by darkdetect!

### CODE REVIEW

**Comment by sumeshir26** [comment]
To apply change, **Unistall** the current installation of TimerX before building the new MSI

**Review by not-nef — APPROVED** [review]
Great! Still have to do some work (Disable "System" option and lokk into why the blur isnt working) but a good start. When do you want to release?

**Comment by sumeshir26** [comment]
@not-nef Check out my new changes

**Comment by sumeshir26** [comment]
It would be nice if the release is out by tomorrow.

Also did you notice that when you switch the theme to dark and restart, the transperency gets lowered to minimum

**Comment by im-coder-lg** [comment]
> Also did you notice that when you switch the theme to dark and restart, the transperency gets lowered to minimum

Same here.

**Comment by im-coder-lg** [comment]
I'll start work on the release notes. If we make it better, it might mean more users.

**Comment by sumeshir26** [comment]
@TimerX-App/reviewers Can you please review? I want to get this merged ASAP

**Comment by im-coder-lg** [comment]
I will do it soon, maybe within 10 minutes! I need to remove every single installation of TimerX, so you'll have to wait.

**Review by im-coder-lg — APPROVED** [review]
I approve. Works on my PC.

**Comment by sumeshir26** [comment]
@not-nef approve this

**Comment by im-coder-lg** [comment]
I think he's at school right now. Wait for some time.

**Comment by im-coder-lg** [comment]
@sumeshir26 I'll just tell, you merge this now. @not-nef seems to be busy, so you merge this. I am almost done on the release notes, will be complete by 9:30 AM IST. You trigger the all-build release action now.

**Comment by sumeshir26** [comment]
Can you merge both PRs and trigger? You cant trigger actions from GH Mobile

**Pull request merged**
