### PR TITLE
perf: Fix performance

### PR DESCRIPTION
**Pull request by sumeshir26**
Heavily WIP. Only Second support as of now

### CODE REVIEW

**Comment by not-nef** [comment]
epic

**Comment by not-nef** [comment]
How do you want to do a millisecond timer? We cant configure the label text for every millisecond?

**Comment by sumeshir26** [comment]
Yeah, or not show it at all. What do you think?

**Comment by im-coder-lg** [comment]
Maybe use an `.after()` loop?

**Comment by im-coder-lg** [comment]
Fixed a merge conflict :)

**Comment by sumeshir26** [comment]
@not-nef The timer dosent loop every millisecond, it just checks the current time and checks it with the time at the start of the timer and subtracts it to get the time passed. Sorry if its confusing

**Comment by not-nef** [comment]
Not confusing at all! Makes perfect sense.

**Comment by im-coder-lg** [comment]
Hey, has anyone invited me on Replit? Got a mail.

**Comment by im-coder-lg** [comment]
Oh nvm, it's our Replit team.

**Comment by im-coder-lg** [comment]
@TimerX-App/reviewers any updates here? Is this ready>

**Comment by sumeshir26** [comment]
No it’s not near ready, it’s going to take about a week more. I’m not at home so I can’t work on TimerX this weekend.

**Comment by im-coder-lg** [comment]
Wow. Alright, I'll try working on something else. Regarding the update system, I frankly need some help. If you could try telling me the next steps, I'll try implementing them.

**Comment by sumeshir26** [comment]
Wait, can you work on the Update system on repl.it so I can help you using repl.it multiplayer

**Comment by im-coder-lg** [comment]
I will start tomorrow. Today's a Sunday.

**Comment by im-coder-lg** [comment]
Are you making progress?

**Comment by sumeshir26** [comment]
@im-coder-lg Yes, after todays commits, it is actuallay usable with pausing! There is just a slight visual glich with pausuing which I will fix tommorow at the latest. That glich is pureley visual and does not affect the actual timer. Can you please test the timer on raspbian?

**Comment by im-coder-lg** [comment]
I'll have to test on Ubuntu, I distro-hopped. But if it works on ARM64, it will work on ARMV7L.

**Comment by im-coder-lg** [comment]
I wish we had users who have macOS Latest so that they could also test, I feel bad for the people left out.

**Comment by sumeshir26** [comment]
Ok, tell me when you test

**Comment by im-coder-lg** [comment]
Hold up, there is Coder, it alows teams to develop programs easily. They have a bunch of Dockerised images, I wonder if a macOS image is also included on it. Then, I could test it, right?

**Comment by sumeshir26** [comment]
Isnt coder paid?

**Comment by im-coder-lg** [comment]
Hold up, there is Coder, it alows teams to develop programs easily. They have a bunch of Dockerised images, I wonder if a macOS image is also included on it. Then, I could test it, right?

**Comment by im-coder-lg** [comment]
Docker deployments, you can take it for testing!

**Comment by im-coder-lg** [comment]
Docker deployments, you can take it for testing!

**Comment by im-coder-lg** [comment]
Wait, you know Coder? Leave it, but I'll search around their registry for macOS images and try installing them. Last time I tried it, it failed horribly.
Also, I don't have a subscription and I don't need one. I'll just host it on a Gitpod container and play around.

**Comment by im-coder-lg** [comment]
Oh turd, latency is high. Wait, I'll test after switching my network.

**Comment by im-coder-lg** [comment]
Also, what do you guys think of a code formatting workflow that uses cron? I think that is more than enough to format our website and our Python code.

**Comment by not-nef** [comment]
Dont know what that is but ok

**Comment by im-coder-lg** [comment]
I have started installing Coder on Gitpod, the dockerised version ofc, maybe we could test on other OSes. There are VNC images too, so we could hopefully succeed in our test.

**Comment by sumeshir26** [comment]
> You know coder?

Github kept reccomending code-server to me

**Comment by im-coder-lg** [comment]
Alright, no macOS :( but we might test on Ubuntu or CentOS(same as Fedora)

**Comment by im-coder-lg** [comment]
> Github kept recommending code-server to me

Wow. Did you see it? Damn, that's the place where I do half my work with other maintainers there, helping them out.
Moreover, code-server and Gitpod are the same, except Gitpod gave you an OS to begin with.

**Comment by im-coder-lg** [comment]
> Dont know what that is but ok

Basically, the `on:` YAML block has a cronjob. It triggers on that specific second. Then, I'll create a PAT here so that the formatter won't throw errors saying that it can't edit some protected files. So, after linking an env secret, I'll commit the file and it will trigger on that moment.

**Comment by im-coder-lg** [comment]
Test still fails. I'll go ahead with adding a Wine setup for TimerX in the docs.

**Comment by sumeshir26** [comment]
@not-nef @im-coder-lg I need some help. When the timer gets paused, the time display slightly changes. I have no idea what is causing this and the timer fixes it after unpausing. Can you please look at the code and see what needs to be changed?

**Comment by im-coder-lg** [comment]
Yessir!

**Comment by im-coder-lg** [comment]
Wait, let's try investigating.
1. Did you add anything to the time display?
2. Did you meddle with any functions the time display uses?
3. Did you try changing the layout?

If you have a yeah for something in this, then edit that code only. If it lingers, think out of that boundary. If it still fails, let's go to StackOverflow.

**Comment by im-coder-lg** [comment]
Also, heads up - I am going to try installing the GItpod app. That's where I code out the website and if that doesn't allow me to push to here, then it will be hard for me to create forks. So, I'll try installing it and I'll test again. If it works, I'll let it be, if now, it's going straight out of here.

**Comment by not-nef** [comment]
> @not-nef @im-coder-lg I need some help. When the timer gets paused, the time display slightly changes. I have no idea what is causing this and the timer fixes it after unpausing. Can you please look at the code and see what needs to be changed?

Wdym it changes?

**Comment by sumeshir26** [comment]
I think I figured out the solution, will commit it tommorow so we can get this  merged by thursday

**Comment by not-nef** [comment]
Cool! Next week i will add the ui to the missing settings and then we are technically ready for 1.1!

**Comment by im-coder-lg** [comment]
When shall we release it?

**Comment by not-nef** [comment]
What about the 16th?

**Comment by im-coder-lg** [comment]
Hmm... @sumeshir26 any ideas?

**Comment by sumeshir26** [comment]
Sure

**Review by not-nef — APPROVED** [review]
LGTM

**Comment by sumeshir26** [comment]
@im-coder-lg Need your review on this!

**Comment by im-coder-lg** [comment]
I need to test this now.

**Review by im-coder-lg — APPROVED** [review]
LGTM! Can you format the code as a clean up commit? Try this batchfile script  out:
```batch
@echo see the commands
pip3 install black isort
black main.py utils.py setup.py
isort main.py utils.py setup.py
REM try making formatting seperately if they throw up stupid errors
REM you must have NPM and NPX, remember that!
npm install -g prettier
REM or
npm install prettier
REM best go with global install
npx prettier --write .
git add .
git commit -m "style: All files"
git push
@echo Done!
```
That's just the code, best add it to TimerX's root. I will make a script for this later.

**Comment by not-nef** [comment]
@im-coder-lg Can you make a formatting workflow for isort and black that runs for every commit? I think that would be useful

**Comment by sumeshir26** [comment]
Will format it tomorrow when I get to my pc.

**Pull request merged**
