### PR TITLE
docs: Adhere to new org change

### PR DESCRIPTION
**Pull request by im-coder-lg**
Changing the docs. I also must add a PR template soon. If there are other links to be changed, tell the website path and I'll fix it!

### CODE REVIEW

**Comment by im-coder-lg** [comment]
Also - don't forget to add yourself to the review team, it would auto-assign(idk how).

**Comment by im-coder-lg** [comment]
Why's Netlify not working?

**Comment by im-coder-lg** [comment]
Yup, Netlify isn't integrated yet. @sumeshir26 it's the same way you started the deployment but when you are going to choose the Git repo from GitHub, click your account name near the repo search bar. Then, click "Add an org" and link this org via the Netlify app. Then choose this repo and deploy.

**Review by not-nef — APPROVED** [review]

**Comment by not-nef** [comment]
Why do macos checks fail for everything?

**Comment by sumeshir26** [comment]
Not sure. Let me look into it

**Comment by not-nef** [comment]
> Not sure. Let me look into it

Found it, you have to include utils.py in setup.py @sumeshir26

**Comment by not-nef** [comment]
i was never a fan of python projects with more than one script

**Comment by not-nef** [comment]
I cant fix it rn, im on the go

**Comment by im-coder-lg** [comment]
Fixed!

**Comment by not-nef** [comment]
Lmao macos checks still fail

**Comment by im-coder-lg** [comment]
Yeah... I will inspect that later.

**Comment by not-nef** [comment]
Please just drop macos support it just brings issues!!

**Comment by im-coder-lg** [comment]
Maybe, thatbseems a really viable option. We could request users to use the Wine compatibility layer. I will research on that and make a documentation page for it by tomorrow in this PR.

**Comment by not-nef** [comment]
Thank you 🙏

**Review by sumeshir26 — APPROVED** [review]
LGTM

**Comment by im-coder-lg** [comment]
Uhm... I was about to add some other changes... I'll commit it directly later.

**Comment by sumeshir26** [comment]
Sorry!

**Comment by im-coder-lg** [comment]
It's fine, I'll directly commit.

**Comment by not-nef** [comment]
> Uhm... I was about to add some other changes...

Thats why drafts exist lmao

**Comment by im-coder-lg** [comment]
I was a bit lazy and overconfident. School started again lol. I will try improving my Gitpod experience, it's hard for me to make PRs all the time. @sumeshir26 can you enable Netlify again?

**Comment by sumeshir26** [comment]
I did that! [timerx-app.netlify.app](timerx-app.netlify.app)

**Comment by im-coder-lg** [comment]
Domain failed... Check Netlify!

**Comment by im-coder-lg** [comment]
Make sure to change the Git repo.

**Pull request merged**
