### PR TITLE
Add better settings

### PR DESCRIPTION
**Pull request by not-nef**
@sumeshir26 This is ready for merging

### CODE REVIEW

**Comment by not-nef** [comment]
With every pr, this app more looks like a uwp app!

**Review by im-coder-lg — APPROVED** [review]
LGTM!

**Comment by not-nef** [comment]
Lets goo

**Comment by im-coder-lg** [comment]
Wait, an even better idea on the about page - why not add it as a tab to the settings window? I will try this though.

**Comment by not-nef** [comment]
> Wait, an even better idea on the about page - why not add it as a tab to the settings window? I will try this though.

I will do it, finish your update system @im-coder-lg

**Comment by not-nef** [comment]
Done! @im-coder-lg

**Comment by im-coder-lg** [comment]
That's great, but why does the font go dark even in dark mode?

**Comment by im-coder-lg** [comment]
> With every pr, this app more looks like a uwp app!

**Comment by im-coder-lg** [comment]
Seems like the installer's the only thing left out though. If we theme that to Sun Valley, it will look great!

**Comment by not-nef** [comment]
> That's great, but why does the clock font go dark even in dark mode?

Oh, have to check

**Comment by not-nef** [comment]
> That's great, but why does the clock font go dark even in dark mode?

What clock font do you mean? Can you send a screenshot?

**Comment by im-coder-lg** [comment]
One min...

**Comment by not-nef** [comment]
Everything seems to work for me

**Comment by im-coder-lg** [comment]
Oh never mind, it's random. So a restart would fix that. Can you check TimerX-App/TimerX-Update-Test#2?

**Comment by not-nef** [comment]
Ah i see what you mean

**Comment by im-coder-lg** [comment]
Anyway, leave it. Soon Windows 7 users will have to switch to Windows 10, so doesn't matter as of now.

**Comment by not-nef** [comment]
> Oh never mind, it's random. So a restart would fix that. Can you check TimerX-App/TimerX-Update-Test#2?

I fixed it!

**Comment by not-nef** [comment]
> Anyway, leave it. Soon Windows 7 users will have to switch to Windows 10, so doesn't matter as of now.

Why?

**Comment by not-nef** [comment]
@im-coder-lg Done!

**Comment by not-nef** [comment]
@sumeshir26 Merge?

**Comment by not-nef** [comment]
@sumeshir26 can i merge?

**Comment by sumeshir26** [comment]
Could you rename the `notebook` to `tabview` or `tabframe` because the name notebook is confusing
 After that, you can merge!

**Review by sumeshir26 — APPROVED** [review]
Epic. Looks gut!

**Comment by sumeshir26** [comment]
Merge this as feat: Settings with Tabs

**Comment by not-nef** [comment]
Okay

**Comment by not-nef** [comment]
My first merge 🎉

**Comment by sumeshir26** [comment]
> My first merge 🎉

Yay!

@not-nef From next time you can just create a branch on the main repo, not your fork so it is easy to manage for everyone

**Pull request merged**
