### PR TITLE
style: The Black formatting. It's neat :+1:

### PR DESCRIPTION
**Pull request by im-coder-lg**

### CODE REVIEW

**Comment by im-coder-lg** [comment]
I don't know what the heck just happened, I wanted it _here_. I hate Gitpod when it comes to this.

**Comment by im-coder-lg** [comment]
Anyone just merge this.

**Comment by im-coder-lg** [comment]
But my work's incomplete.

**Comment by sumeshir26** [comment]
Merge or Not?

**Comment by im-coder-lg** [comment]
Next commit is for the website.

**Comment by im-coder-lg** [comment]
Yes. I am in a dilemma.

**Pull request merged**
